scenarioName: "scenario-100"
outputDir: "scenarios"
# The following are the default values for the scenario generation
generation:
  numPodEvents: 100
  arrivalScale: 2.0
  arrivalScaleFactor:  5.0
  durationScale: 1.5
  durationShape: 2.0
  durationScaleFactor: 10.0
  podCpuShape: 3.0
  podCpuFactor: 1.0
  podMemScale: 2.0
  podMemShape: 512.0
  podMemFactor: 1.0